#!/bin/bash

set -e

DPMS_STANDBY_TIME=${DPMS_STANDBY_TIME:-300}
DPMS_SUSPEND_TIME=${DPMS_SUSPEND_TIME:-300}
DPMS_OFF_TIME=${DPMS_OFF_TIME:-300}
DPMS_WATCHDOG_SLEEP_TIME=${DPMS_WATCHDOG_SLEEP_TIME:-300}

while true
do
	xset dpms "$DPMS_STANDBY_TIME" "$DPMS_SUSPEND_TIME" "$DPMS_OFF_TIME"
	sleep "$DPMS_WATCHDOG_SLEEP_TIME"
done

